### ISSUE TITLE
[Question] How can i use it?

### ISSUE THREAD

**Issue by Virtual0txt** [Hermanoid/NotEnoughRecipeDumps#1]
Hey,
I was looking for something like this for some time and I was nearly going to implement that myself.
This look great, I could help you and implement some fixes to make the output more clear.
I have just some questions:
Could you tell me how can i use it to dump json ?
Does this work with new version of mc 1.21 ?

**Comment by Virtual0txt** [comment]
nvm i read all readme again, so just second question is important to me

**Comment by Hermanoid** [comment]
It adds an option to the NEI export menu GUI to export recipes to JSON.
As for MC versions, I'm not very familiar with how compatibility works between versions of MC. But, the mod template I used is specifically for 1.7.10, and the NEI version I'm targeting is the one used by GTNH. It's a simple enough mod but I'm guessing it won't transfer to 1.21 directly.

**Comment by Hermanoid** [comment]
Closing because old
